(setq pera 6)
(+25)
(defun flores (x)
  (* 3 x))
(flores 3)
(cond (question1 answer1)
  (question2 answer2)
  (else else_answer))
(< 6 9)
(equal 5 9)
(* 9 8)
(+ 5 (* 2 33))
(list perro gato amarillo)
(atom l)